services:
  - type: web
    name: ats-ai-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt && python -m spacy download en_core_web_sm
    startCommand: cd backend && python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false  # You'll set this in Render dashboard
